---
fixes:
  - |
    Fixes `bug 1668978 <https://bugs.launchpad.net/tripleo/+bug/1668978>`__
    Make the process for adding support for a new language (i18n) simpler by
    reducing the number of steps necessary.  This change modifies the format of
    the ``language`` setting in the main configuration file from a list to an
    object.
