- project:
    name: openstack/tripleo-ui
    templates:
       - tripleo-undercloud-jobs
    check:
      jobs:
        # Only run the undercloud-oooq job
        - tripleo-ci-centos-7-undercloud-oooq:
            files:
              - ^src/.*$
        - tripleo-ci-centos-7-undercloud-upgrades:
            files:
              - $^
        - tripleo-ci-centos-7-undercloud-containers:
            files:
              - $^
    gate:
      queue: tripleo
      jobs:
        # Only run the undercloud-oooq job
        - tripleo-ci-centos-7-undercloud-oooq:
            files:
              - ^src/.*$
        - tripleo-ci-centos-7-undercloud-upgrades:
            files:
              - $^
        - tripleo-ci-centos-7-undercloud-containers:
            files:
              - $^
