- project:
    templates:
      - nodejs8-jobs
      - nodejs8-publish-to-npm
      - release-notes-jobs-python3
    check:
      jobs:
        - tripleo-ci-centos-7-undercloud-containers:
            files:
              - ^src/.*$
              - ^webpack.*$
              - ^package.json$
              - ^npm-shrinkwrap.json$
              - ^.babelrc$
    gate:
      queue: tripleo
      jobs:
        - tripleo-ci-centos-7-undercloud-containers:
            files:
              - ^src/.*$
              - ^webpack.*$
              - ^package.json$
              - ^npm-shrinkwrap.json$
              - ^.babelrc$
