import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_VALIDATIONS_PENDING: null,
  FETCH_VALIDATIONS_SUCCESS: null,
  FETCH_VALIDATIONS_FAILED: null,
  SHOW_VALIDATION_STAGE: null,
  TOGGLE_VALIDATION_STAGE_VISIBILITY: null,
  UPDATE_STAGE_STATUS: null,
  UPDATE_VALIDATION_STATUS: null
});
