import keyMirror from 'keymirror';

export default keyMirror({
  FETCH_WORKFLOW_EXECUTIONS_PENDING: null,
  FETCH_WORKFLOW_EXECUTIONS_SUCCESS: null,
  FETCH_WORKFLOW_EXECUTIONS_FAILED: null,
  ADD_WORKFLOW_EXECUTION: null,
  ADD_WORKFLOW_EXECUTION_FROM_MESSAGE: null
});
